// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cashflows.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCashflow = `-- name: CreateCashflow :exec
INSERT INTO cashflows (
    id, user_id, portfolio_id, type, amount, currency, description, executed_at, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateCashflowParams struct {
	ID          pgtype.UUID      `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	PortfolioID pgtype.UUID      `json:"portfolio_id"`
	Type        string           `json:"type"`
	Amount      pgtype.Numeric   `json:"amount"`
	Currency    string           `json:"currency"`
	Description string           `json:"description"`
	ExecutedAt  pgtype.Timestamp `json:"executed_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateCashflow(ctx context.Context, arg CreateCashflowParams) error {
	_, err := q.db.Exec(ctx, createCashflow,
		arg.ID,
		arg.UserID,
		arg.PortfolioID,
		arg.Type,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.ExecutedAt,
		arg.CreatedAt,
	)
	return err
}

const deleteCashflow = `-- name: DeleteCashflow :exec
DELETE FROM cashflows WHERE id = $1
`

func (q *Queries) DeleteCashflow(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCashflow, id)
	return err
}

const listCashflowsByUserID = `-- name: ListCashflowsByUserID :many
SELECT id, user_id, portfolio_id, type, amount, currency, description, executed_at, created_at 
FROM cashflows
WHERE user_id = $1
ORDER BY executed_at DESC
`

func (q *Queries) ListCashflowsByUserID(ctx context.Context, userID pgtype.UUID) ([]Cashflow, error) {
	rows, err := q.db.Query(ctx, listCashflowsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cashflow
	for rows.Next() {
		var i Cashflow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PortfolioID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.ExecutedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
