// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: holdings.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHolding = `-- name: CreateHolding :one
INSERT INTO holdings (portfolio_id, symbol, name, asset_type, quantity, avg_buy_price, current_price)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, portfolio_id, symbol, name, asset_type, quantity, avg_buy_price, current_price, created_at, updated_at
`

type CreateHoldingParams struct {
	PortfolioID  pgtype.UUID `json:"portfolio_id"`
	Symbol       string      `json:"symbol"`
	Name         string      `json:"name"`
	AssetType    string      `json:"asset_type"`
	Quantity     float64     `json:"quantity"`
	AvgBuyPrice  float64     `json:"avg_buy_price"`
	CurrentPrice float64     `json:"current_price"`
}

func (q *Queries) CreateHolding(ctx context.Context, arg CreateHoldingParams) (Holding, error) {
	row := q.db.QueryRow(ctx, createHolding,
		arg.PortfolioID,
		arg.Symbol,
		arg.Name,
		arg.AssetType,
		arg.Quantity,
		arg.AvgBuyPrice,
		arg.CurrentPrice,
	)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Symbol,
		&i.Name,
		&i.AssetType,
		&i.Quantity,
		&i.AvgBuyPrice,
		&i.CurrentPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHolding = `-- name: DeleteHolding :exec
DELETE FROM holdings WHERE id = $1
`

func (q *Queries) DeleteHolding(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteHolding, id)
	return err
}

const getHoldingByID = `-- name: GetHoldingByID :one
SELECT id, portfolio_id, symbol, name, asset_type, quantity, avg_buy_price, current_price, created_at, updated_at
FROM holdings WHERE id = $1
`

func (q *Queries) GetHoldingByID(ctx context.Context, id pgtype.UUID) (Holding, error) {
	row := q.db.QueryRow(ctx, getHoldingByID, id)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Symbol,
		&i.Name,
		&i.AssetType,
		&i.Quantity,
		&i.AvgBuyPrice,
		&i.CurrentPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHoldingsByPortfolioID = `-- name: ListHoldingsByPortfolioID :many
SELECT id, portfolio_id, symbol, name, asset_type, quantity, avg_buy_price, current_price, created_at, updated_at
FROM holdings WHERE portfolio_id = $1 ORDER BY symbol ASC
`

func (q *Queries) ListHoldingsByPortfolioID(ctx context.Context, portfolioID pgtype.UUID) ([]Holding, error) {
	rows, err := q.db.Query(ctx, listHoldingsByPortfolioID, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Holding
	for rows.Next() {
		var i Holding
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.Symbol,
			&i.Name,
			&i.AssetType,
			&i.Quantity,
			&i.AvgBuyPrice,
			&i.CurrentPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHolding = `-- name: UpdateHolding :exec
UPDATE holdings SET symbol = $2, name = $3, asset_type = $4, quantity = $5,
    avg_buy_price = $6, current_price = $7, updated_at = NOW()
WHERE id = $1
`

type UpdateHoldingParams struct {
	ID           pgtype.UUID `json:"id"`
	Symbol       string      `json:"symbol"`
	Name         string      `json:"name"`
	AssetType    string      `json:"asset_type"`
	Quantity     float64     `json:"quantity"`
	AvgBuyPrice  float64     `json:"avg_buy_price"`
	CurrentPrice float64     `json:"current_price"`
}

func (q *Queries) UpdateHolding(ctx context.Context, arg UpdateHoldingParams) error {
	_, err := q.db.Exec(ctx, updateHolding,
		arg.ID,
		arg.Symbol,
		arg.Name,
		arg.AssetType,
		arg.Quantity,
		arg.AvgBuyPrice,
		arg.CurrentPrice,
	)
	return err
}
