// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cashflow struct {
	ID          pgtype.UUID      `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	PortfolioID pgtype.UUID      `json:"portfolio_id"`
	Type        string           `json:"type"`
	Amount      pgtype.Numeric   `json:"amount"`
	Currency    string           `json:"currency"`
	Description string           `json:"description"`
	ExecutedAt  pgtype.Timestamp `json:"executed_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Holding struct {
	ID           pgtype.UUID        `json:"id"`
	PortfolioID  pgtype.UUID        `json:"portfolio_id"`
	Symbol       string             `json:"symbol"`
	Name         string             `json:"name"`
	AssetType    string             `json:"asset_type"`
	Quantity     float64            `json:"quantity"`
	AvgBuyPrice  float64            `json:"avg_buy_price"`
	CurrentPrice float64            `json:"current_price"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Notification struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Title     string           `json:"title"`
	Message   string           `json:"message"`
	IsRead    bool             `json:"is_read"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Portfolio struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Currency    string             `json:"currency"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Server struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Name          string             `json:"name"`
	Host          string             `json:"host"`
	Port          int32              `json:"port"`
	Type          string             `json:"type"`
	Status        string             `json:"status"`
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ServiceCheck struct {
	ID              pgtype.UUID        `json:"id"`
	ServerID        pgtype.UUID        `json:"server_id"`
	Name            string             `json:"name"`
	Endpoint        string             `json:"endpoint"`
	Method          string             `json:"method"`
	ExpectedStatus  int32              `json:"expected_status"`
	IntervalSeconds int32              `json:"interval_seconds"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID         pgtype.UUID        `json:"id"`
	HoldingID  pgtype.UUID        `json:"holding_id"`
	Type       string             `json:"type"`
	Quantity   float64            `json:"quantity"`
	Price      float64            `json:"price"`
	Fee        float64            `json:"fee"`
	Notes      string             `json:"notes"`
	ExecutedAt pgtype.Timestamptz `json:"executed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type UptimeLog struct {
	ID             pgtype.UUID        `json:"id"`
	ServiceCheckID pgtype.UUID        `json:"service_check_id"`
	Status         string             `json:"status"`
	StatusCode     int32              `json:"status_code"`
	ResponseTimeMs int32              `json:"response_time_ms"`
	ErrorMessage   string             `json:"error_message"`
	CheckedAt      pgtype.Timestamptz `json:"checked_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
