// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (
    id, user_id, title, message, is_read, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateNotificationParams struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Title     string           `json:"title"`
	Message   string           `json:"message"`
	IsRead    bool             `json:"is_read"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Message,
		arg.IsRead,
		arg.CreatedAt,
	)
	return err
}

const listNotificationsByUserID = `-- name: ListNotificationsByUserID :many
SELECT id, user_id, title, message, is_read, created_at
FROM notifications
WHERE user_id = $1 AND ($2::boolean = false OR is_read = false)
ORDER BY created_at DESC
`

type ListNotificationsByUserIDParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Column2 bool        `json:"column_2"`
}

func (q *Queries) ListNotificationsByUserID(ctx context.Context, arg ListNotificationsByUserIDParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUserID, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications 
SET is_read = true 
WHERE id = $1 AND user_id = $2
`

type MarkNotificationAsReadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	return err
}
