// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portfolios.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPortfolio = `-- name: CreatePortfolio :one
INSERT INTO portfolios (user_id, name, description, currency)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, description, currency, created_at, updated_at
`

type CreatePortfolioParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Currency    string      `json:"currency"`
}

func (q *Queries) CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error) {
	row := q.db.QueryRow(ctx, createPortfolio,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Currency,
	)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePortfolio = `-- name: DeletePortfolio :exec
DELETE FROM portfolios WHERE id = $1
`

func (q *Queries) DeletePortfolio(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePortfolio, id)
	return err
}

const getPortfolioByID = `-- name: GetPortfolioByID :one
SELECT id, user_id, name, description, currency, created_at, updated_at
FROM portfolios WHERE id = $1
`

func (q *Queries) GetPortfolioByID(ctx context.Context, id pgtype.UUID) (Portfolio, error) {
	row := q.db.QueryRow(ctx, getPortfolioByID, id)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPortfolioSummary = `-- name: GetPortfolioSummary :one
SELECT
    p.id AS portfolio_id,
    COALESCE(SUM(h.quantity * h.current_price), 0)::DOUBLE PRECISION AS total_value,
    COALESCE(SUM(h.quantity * h.avg_buy_price), 0)::DOUBLE PRECISION AS total_cost,
    COUNT(h.id)::INTEGER AS holding_count
FROM portfolios p
LEFT JOIN holdings h ON h.portfolio_id = p.id
WHERE p.id = $1
GROUP BY p.id
`

type GetPortfolioSummaryRow struct {
	PortfolioID  pgtype.UUID `json:"portfolio_id"`
	TotalValue   float64     `json:"total_value"`
	TotalCost    float64     `json:"total_cost"`
	HoldingCount int32       `json:"holding_count"`
}

func (q *Queries) GetPortfolioSummary(ctx context.Context, id pgtype.UUID) (GetPortfolioSummaryRow, error) {
	row := q.db.QueryRow(ctx, getPortfolioSummary, id)
	var i GetPortfolioSummaryRow
	err := row.Scan(
		&i.PortfolioID,
		&i.TotalValue,
		&i.TotalCost,
		&i.HoldingCount,
	)
	return i, err
}

const listPortfoliosByUserID = `-- name: ListPortfoliosByUserID :many
SELECT id, user_id, name, description, currency, created_at, updated_at
FROM portfolios WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPortfoliosByUserID(ctx context.Context, userID pgtype.UUID) ([]Portfolio, error) {
	rows, err := q.db.Query(ctx, listPortfoliosByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Portfolio
	for rows.Next() {
		var i Portfolio
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePortfolio = `-- name: UpdatePortfolio :exec
UPDATE portfolios SET name = $2, description = $3, currency = $4, updated_at = NOW()
WHERE id = $1
`

type UpdatePortfolioParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Currency    string      `json:"currency"`
}

func (q *Queries) UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) error {
	_, err := q.db.Exec(ctx, updatePortfolio,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Currency,
	)
	return err
}
