// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCashflow(ctx context.Context, arg CreateCashflowParams) error
	CreateHolding(ctx context.Context, arg CreateHoldingParams) (Holding, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) error
	CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error)
	CreateServer(ctx context.Context, arg CreateServerParams) (Server, error)
	CreateServiceCheck(ctx context.Context, arg CreateServiceCheckParams) (ServiceCheck, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUptimeLog(ctx context.Context, arg CreateUptimeLogParams) (UptimeLog, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCashflow(ctx context.Context, id pgtype.UUID) error
	DeleteHolding(ctx context.Context, id pgtype.UUID) error
	DeletePortfolio(ctx context.Context, id pgtype.UUID) error
	DeleteServer(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetDashboardOverview(ctx context.Context, userID pgtype.UUID) (GetDashboardOverviewRow, error)
	GetHoldingByID(ctx context.Context, id pgtype.UUID) (Holding, error)
	GetPortfolioByID(ctx context.Context, id pgtype.UUID) (Portfolio, error)
	GetPortfolioSummary(ctx context.Context, id pgtype.UUID) (GetPortfolioSummaryRow, error)
	GetServerByID(ctx context.Context, id pgtype.UUID) (Server, error)
	GetServiceCheckByID(ctx context.Context, id pgtype.UUID) (ServiceCheck, error)
	GetUptimeByServerID(ctx context.Context, arg GetUptimeByServerIDParams) ([]UptimeLog, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListActiveServiceChecks(ctx context.Context) ([]ServiceCheck, error)
	ListCashflowsByUserID(ctx context.Context, userID pgtype.UUID) ([]Cashflow, error)
	ListHoldingsByPortfolioID(ctx context.Context, portfolioID pgtype.UUID) ([]Holding, error)
	ListNotificationsByUserID(ctx context.Context, arg ListNotificationsByUserIDParams) ([]Notification, error)
	ListPortfoliosByUserID(ctx context.Context, userID pgtype.UUID) ([]Portfolio, error)
	ListServersByUserID(ctx context.Context, userID pgtype.UUID) ([]Server, error)
	ListServiceChecksByServerID(ctx context.Context, serverID pgtype.UUID) ([]ServiceCheck, error)
	ListTransactionsByHoldingID(ctx context.Context, holdingID pgtype.UUID) ([]Transaction, error)
	ListUptimeLogsByServiceCheckID(ctx context.Context, arg ListUptimeLogsByServiceCheckIDParams) ([]UptimeLog, error)
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error
	UpdateHolding(ctx context.Context, arg UpdateHoldingParams) error
	UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) error
	UpdateServer(ctx context.Context, arg UpdateServerParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
