// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_checks.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createServiceCheck = `-- name: CreateServiceCheck :one
INSERT INTO service_checks (server_id, name, endpoint, method, expected_status, interval_seconds, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, server_id, name, endpoint, method, expected_status, interval_seconds, is_active, created_at
`

type CreateServiceCheckParams struct {
	ServerID        pgtype.UUID `json:"server_id"`
	Name            string      `json:"name"`
	Endpoint        string      `json:"endpoint"`
	Method          string      `json:"method"`
	ExpectedStatus  int32       `json:"expected_status"`
	IntervalSeconds int32       `json:"interval_seconds"`
	IsActive        bool        `json:"is_active"`
}

func (q *Queries) CreateServiceCheck(ctx context.Context, arg CreateServiceCheckParams) (ServiceCheck, error) {
	row := q.db.QueryRow(ctx, createServiceCheck,
		arg.ServerID,
		arg.Name,
		arg.Endpoint,
		arg.Method,
		arg.ExpectedStatus,
		arg.IntervalSeconds,
		arg.IsActive,
	)
	var i ServiceCheck
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Endpoint,
		&i.Method,
		&i.ExpectedStatus,
		&i.IntervalSeconds,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getServiceCheckByID = `-- name: GetServiceCheckByID :one
SELECT id, server_id, name, endpoint, method, expected_status, interval_seconds, is_active, created_at
FROM service_checks WHERE id = $1
`

func (q *Queries) GetServiceCheckByID(ctx context.Context, id pgtype.UUID) (ServiceCheck, error) {
	row := q.db.QueryRow(ctx, getServiceCheckByID, id)
	var i ServiceCheck
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Endpoint,
		&i.Method,
		&i.ExpectedStatus,
		&i.IntervalSeconds,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveServiceChecks = `-- name: ListActiveServiceChecks :many
SELECT id, server_id, name, endpoint, method, expected_status, interval_seconds, is_active, created_at
FROM service_checks WHERE is_active = true
`

func (q *Queries) ListActiveServiceChecks(ctx context.Context) ([]ServiceCheck, error) {
	rows, err := q.db.Query(ctx, listActiveServiceChecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceCheck
	for rows.Next() {
		var i ServiceCheck
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.Endpoint,
			&i.Method,
			&i.ExpectedStatus,
			&i.IntervalSeconds,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceChecksByServerID = `-- name: ListServiceChecksByServerID :many
SELECT id, server_id, name, endpoint, method, expected_status, interval_seconds, is_active, created_at
FROM service_checks WHERE server_id = $1 ORDER BY name ASC
`

func (q *Queries) ListServiceChecksByServerID(ctx context.Context, serverID pgtype.UUID) ([]ServiceCheck, error) {
	rows, err := q.db.Query(ctx, listServiceChecksByServerID, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceCheck
	for rows.Next() {
		var i ServiceCheck
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.Endpoint,
			&i.Method,
			&i.ExpectedStatus,
			&i.IntervalSeconds,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
