// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: servers.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createServer = `-- name: CreateServer :one
INSERT INTO servers (user_id, name, host, port, type, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, host, port, type, status, last_checked_at, created_at, updated_at
`

type CreateServerParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Host   string      `json:"host"`
	Port   int32       `json:"port"`
	Type   string      `json:"type"`
	Status string      `json:"status"`
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer,
		arg.UserID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Type,
		arg.Status,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Type,
		&i.Status,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteServer = `-- name: DeleteServer :exec
DELETE FROM servers WHERE id = $1
`

func (q *Queries) DeleteServer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteServer, id)
	return err
}

const getDashboardOverview = `-- name: GetDashboardOverview :one
SELECT
    (SELECT COUNT(*)::INTEGER FROM portfolios WHERE portfolios.user_id = $1) AS total_portfolios,
    COALESCE((SELECT SUM(h.quantity * h.current_price) FROM holdings h
        JOIN portfolios p ON p.id = h.portfolio_id WHERE p.user_id = $1), 0)::DOUBLE PRECISION AS total_value,
    (SELECT COUNT(*)::INTEGER FROM servers WHERE servers.user_id = $1) AS total_servers,
    (SELECT COUNT(*)::INTEGER FROM servers WHERE servers.user_id = $1 AND status = 'online') AS servers_online,
    (SELECT COUNT(*)::INTEGER FROM servers WHERE servers.user_id = $1 AND status = 'offline') AS servers_offline,
    (SELECT COUNT(*)::INTEGER FROM servers WHERE servers.user_id = $1 AND status = 'degraded') AS servers_degraded
`

type GetDashboardOverviewRow struct {
	TotalPortfolios int32   `json:"total_portfolios"`
	TotalValue      float64 `json:"total_value"`
	TotalServers    int32   `json:"total_servers"`
	ServersOnline   int32   `json:"servers_online"`
	ServersOffline  int32   `json:"servers_offline"`
	ServersDegraded int32   `json:"servers_degraded"`
}

func (q *Queries) GetDashboardOverview(ctx context.Context, userID pgtype.UUID) (GetDashboardOverviewRow, error) {
	row := q.db.QueryRow(ctx, getDashboardOverview, userID)
	var i GetDashboardOverviewRow
	err := row.Scan(
		&i.TotalPortfolios,
		&i.TotalValue,
		&i.TotalServers,
		&i.ServersOnline,
		&i.ServersOffline,
		&i.ServersDegraded,
	)
	return i, err
}

const getServerByID = `-- name: GetServerByID :one
SELECT id, user_id, name, host, port, type, status, last_checked_at, created_at, updated_at
FROM servers WHERE id = $1
`

func (q *Queries) GetServerByID(ctx context.Context, id pgtype.UUID) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByID, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Type,
		&i.Status,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServersByUserID = `-- name: ListServersByUserID :many
SELECT id, user_id, name, host, port, type, status, last_checked_at, created_at, updated_at
FROM servers WHERE user_id = $1 ORDER BY name ASC
`

func (q *Queries) ListServersByUserID(ctx context.Context, userID pgtype.UUID) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Server
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Type,
			&i.Status,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServer = `-- name: UpdateServer :exec
UPDATE servers SET name = $2, host = $3, port = $4, type = $5, status = $6,
    last_checked_at = $7, updated_at = NOW()
WHERE id = $1
`

type UpdateServerParams struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Host          string             `json:"host"`
	Port          int32              `json:"port"`
	Type          string             `json:"type"`
	Status        string             `json:"status"`
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
}

func (q *Queries) UpdateServer(ctx context.Context, arg UpdateServerParams) error {
	_, err := q.db.Exec(ctx, updateServer,
		arg.ID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Type,
		arg.Status,
		arg.LastCheckedAt,
	)
	return err
}
