// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (holding_id, type, quantity, price, fee, notes, executed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, holding_id, type, quantity, price, fee, notes, executed_at, created_at
`

type CreateTransactionParams struct {
	HoldingID  pgtype.UUID        `json:"holding_id"`
	Type       string             `json:"type"`
	Quantity   float64            `json:"quantity"`
	Price      float64            `json:"price"`
	Fee        float64            `json:"fee"`
	Notes      string             `json:"notes"`
	ExecutedAt pgtype.Timestamptz `json:"executed_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.HoldingID,
		arg.Type,
		arg.Quantity,
		arg.Price,
		arg.Fee,
		arg.Notes,
		arg.ExecutedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.HoldingID,
		&i.Type,
		&i.Quantity,
		&i.Price,
		&i.Fee,
		&i.Notes,
		&i.ExecutedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionsByHoldingID = `-- name: ListTransactionsByHoldingID :many
SELECT id, holding_id, type, quantity, price, fee, notes, executed_at, created_at
FROM transactions WHERE holding_id = $1 ORDER BY executed_at DESC
`

func (q *Queries) ListTransactionsByHoldingID(ctx context.Context, holdingID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByHoldingID, holdingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.HoldingID,
			&i.Type,
			&i.Quantity,
			&i.Price,
			&i.Fee,
			&i.Notes,
			&i.ExecutedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
