// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uptime_logs.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUptimeLog = `-- name: CreateUptimeLog :one
INSERT INTO uptime_logs (service_check_id, status, status_code, response_time_ms, error_message, checked_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, service_check_id, status, status_code, response_time_ms, error_message, checked_at
`

type CreateUptimeLogParams struct {
	ServiceCheckID pgtype.UUID        `json:"service_check_id"`
	Status         string             `json:"status"`
	StatusCode     int32              `json:"status_code"`
	ResponseTimeMs int32              `json:"response_time_ms"`
	ErrorMessage   string             `json:"error_message"`
	CheckedAt      pgtype.Timestamptz `json:"checked_at"`
}

func (q *Queries) CreateUptimeLog(ctx context.Context, arg CreateUptimeLogParams) (UptimeLog, error) {
	row := q.db.QueryRow(ctx, createUptimeLog,
		arg.ServiceCheckID,
		arg.Status,
		arg.StatusCode,
		arg.ResponseTimeMs,
		arg.ErrorMessage,
		arg.CheckedAt,
	)
	var i UptimeLog
	err := row.Scan(
		&i.ID,
		&i.ServiceCheckID,
		&i.Status,
		&i.StatusCode,
		&i.ResponseTimeMs,
		&i.ErrorMessage,
		&i.CheckedAt,
	)
	return i, err
}

const getUptimeByServerID = `-- name: GetUptimeByServerID :many
SELECT ul.id, ul.service_check_id, ul.status, ul.status_code, ul.response_time_ms, ul.error_message, ul.checked_at
FROM uptime_logs ul
JOIN service_checks sc ON sc.id = ul.service_check_id
WHERE sc.server_id = $1
ORDER BY ul.checked_at DESC LIMIT $2
`

type GetUptimeByServerIDParams struct {
	ServerID pgtype.UUID `json:"server_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) GetUptimeByServerID(ctx context.Context, arg GetUptimeByServerIDParams) ([]UptimeLog, error) {
	rows, err := q.db.Query(ctx, getUptimeByServerID, arg.ServerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UptimeLog
	for rows.Next() {
		var i UptimeLog
		if err := rows.Scan(
			&i.ID,
			&i.ServiceCheckID,
			&i.Status,
			&i.StatusCode,
			&i.ResponseTimeMs,
			&i.ErrorMessage,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUptimeLogsByServiceCheckID = `-- name: ListUptimeLogsByServiceCheckID :many
SELECT id, service_check_id, status, status_code, response_time_ms, error_message, checked_at
FROM uptime_logs WHERE service_check_id = $1
ORDER BY checked_at DESC LIMIT $2
`

type ListUptimeLogsByServiceCheckIDParams struct {
	ServiceCheckID pgtype.UUID `json:"service_check_id"`
	Limit          int32       `json:"limit"`
}

func (q *Queries) ListUptimeLogsByServiceCheckID(ctx context.Context, arg ListUptimeLogsByServiceCheckIDParams) ([]UptimeLog, error) {
	rows, err := q.db.Query(ctx, listUptimeLogsByServiceCheckID, arg.ServiceCheckID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UptimeLog
	for rows.Next() {
		var i UptimeLog
		if err := rows.Scan(
			&i.ID,
			&i.ServiceCheckID,
			&i.Status,
			&i.StatusCode,
			&i.ResponseTimeMs,
			&i.ErrorMessage,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
